const express = require('express')
const router = express.Router()
const {getRoute,getByIdRoute,postRoute,putRoute,patchRoute, deleteRoute} = require('../Controllers/egController')
router.get('/get',getRoute)
router.get('get/:id',getByIdRoute)
router.post('/post',postRoute)
router.put('/put/:id',putRoute)
router.patch('/patch',patchRoute)
router.delete('/delete',deleteRoute)
module.exports = router